services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASS: ""

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pokemon_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    volumes:
      - ./public/swagger/swagger.yaml:/swagger/swagger.yaml:ro

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  db_sonar:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db_sonar:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
    depends_on:
      - db_sonar

volumes:
  db_data:
  sonar_data:
  sonar_db_data:
